### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by magnum** [Arcath/sass-watch#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.2
**Thrown From**: [sass-watch](https://github.com/arcath/sass-watch) package, v0.2.0
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/magnum/.atom/packages/sass-watch/lib/watcher-view.coffee:37

TypeError: undefined is not a function
  at WatcherView.module.exports.WatcherView.stopWatcher (/Users/magnum/.atom/packages/sass-watch/lib/watcher-view.coffee:37:43)
  at HTMLButtonElement.<anonymous> (/Users/magnum/.atom/packages/sass-watch/node_modules/space-pen/lib/space-pen.js:214:36)
  at HTMLButtonElement.jQuery.event.dispatch (/Users/magnum/.atom/packages/sass-watch/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLButtonElement.elemData.handle (/Users/magnum/.atom/packages/sass-watch/node_modules/space-pen/vendor/jquery.js:4360:46)

```
### Commands

```
     -0:51.4 core:move-right (atom-text-editor.editor.mini)
 15x -0:51.0 core:backspace (atom-text-editor.editor.mini)
     -0:44.7 core:confirm (atom-text-editor.editor.mini)
  3x -0:37.5 core:save (atom-text-editor.editor.is-focused)
  3x -0:22.3 inline-autocomplete:cycle (atom-text-editor.editor.is-focused)
     -0:15.1 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:12.9 core:move-down (atom-text-editor.editor.mini)
     -0:12.3 core:confirm (atom-text-editor.editor.mini)
     -0:12.3 sass-watch:watch (atom-text-editor.editor.is-focused)
     -0:11.5 editor:consolidate-selections (atom-text-editor.editor.mini)
     -0:11.5 core:cancel (atom-text-editor.editor.mini)
     -0:10.8 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:08.3 core:backspace (atom-text-editor.editor.mini)
     -0:07.5 core:confirm (atom-text-editor.editor.mini)
     -0:07.5 sass-watch:list (atom-text-editor.editor.is-focused)
     -0:06.6 core:confirm (atom-text-editor.editor.mini)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autocomplete-paths",
      "autocomplete-plus",
      "symbols-view"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```
### Installed Packages

``` coffee
# User
atom-ctags, v2.6.0
atomatigit, v1.2.3
autocomplete-css, v0.4.0
autocomplete-html, v0.3.0
autocomplete-ruby, v0.0.1
color-picker, v1.4.4
compare-files, v0.4.1
git-diff-details, v0.6.0
git-log, v0.3.0
html2haml, v0.6.0
inline-autocomplete, v1.0.4
language-haml, v0.15.0
linter, v0.12.0
minimap, v4.6.0
sass-watch, v0.2.0

# Dev
No dev packages
```

**Comment by Arcath** [comment]
What are the steps to reproduce? looking at the stack trace were you trying to stop watching a file from the watcher list view?

**Comment by magnum** [comment]
yes

On Thu, Mar 12, 2015 at 11:06 AM, Adam Laycock notifications@github.com
wrote:

> What are the steps to reproduce? looking at the stack trace were you
> trying to stop watching a file from the watcher list view?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Arcath/sass-watch/issues/4#issuecomment-78452603.

## 

Antonio Molinari
+39 335 5495324
http://www.incode.it
