### ISSUE TITLE
Module not found if Windows .atom path contains a space

### ISSUE THREAD

**Issue by Emily-Steel** [Arcath/sass-watch#6]
The title says it all.

```
SASS Compile Failed
Command failed: C:\Windows\system32\cmd.exe /s /c "E:\nodejs\node.exe C:\Users\Christopher Steel\.atom\packages\sass-watch\node_modules\node-sass\bin\node-sass "E:\wamp\www\h2d\wp-content\themes\h2dconseil\scss\layout.scss" "E:\wamp\www\h2d\wp-content\themes\h2dconseil\css\layout.css""
module.js:338
    throw err;
          ^
Error: Cannot find module 'C:\Users\Christopher'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by Arcath** [comment]
I will add some quoting to the commands as soon as I can. Sorry about that.
